### ISSUE TITLE
WPML Compatibility

### ISSUE THREAD

**Issue by EkoJr** [Advanced-Post-List/advanced-post-list#96]
**NOTE TO WPML Devs:** Majority of the issues may have been solved. Need to test and will upload changes.  I'll update this note every 12-24 hours *(10/23/17 3:00pm UTC)*

In (Alpha) 0.4, the Preset Post List conversion to Post Data added some incompatibility issues with WPML. This is both considered a Blocker Defect and a Support Feature.

* [Resolved] ~Outputting post content/metadata is bugged with internal shortcodes (I imagine this is fairly common and has documentation somewhere).~
* [Resolved] ~Unable to Translate APL_Design Post Metadata; while inside CPT apl_post_list editor.~
* [Resolved] ~Exporting Data in the Settings page has a Trivial Bug.~
  * NOTE: There are two CPTs being exported. APL_Post_List and APL_Design.
  * NOTE: Both CPT posts have the same name.
  * APL Post Lists exports properly, but APL_Design is unable to query in order set object.

Additional Notes
* APL_Post_List Post Data does not have any strings to translate. To the best of my knowledge. It is strictly intended for configurations.
* APL_Designs will have Dynamic strings to translate, while using Static internal-shortcodes.
* Options Database is 'apl_options' and does have 1 string to translate.

Dev Notes
* Adding the `wpml-config.xml` seemed to fix majority of the issues.

## Todo List

- [x] Internal Shortcodes grabs the already translated (trans) page data.
- [ ] (AUTHOR/DEV) MAYBE add General Setting to decide what to do if no trans data exists. Either **Nothing** or **Main Lang**. Or does SitePress handle it automatically? 
- [X] Add WPML-Config file.
- [X] ~?? WPML Register String with APL_Design{ apl_before, apl_content, apl_after, & apl_empty }?~
- [x] Prevent being able to translate APL_Filter. Prefix similar to 'apl_(query_args key)`.
- [ ] In wp_options, `['apl_options']['empty_message']` needs to register translation.
- [ ] Multilingual Taxonomies & Terms (possible pushback)

**Comment by EkoJr** [comment]
## APL Design Class

There are multiple flaws being produced with an alternate concept with Custom Post Types (CPTs). Loosely named: Child Post Type, Twin Post Types, etc.

This concept has to remain for future implementation, but at the same time can be modified in the same area and to keep separate.

### Ideas and Solutions

* Create and Add an Admin Page instead of using the (backend menu functionality) built-in Post Type Editor. 
NOTE: Similar Concept already applied to Settings, HOWEVER, post data functionality is stripped.
NOTE: It's planned to have Separate Post Data functionality anyways.
* Change Register Post Type to allow editor access, BUT limit the amount of access (Ex. NO Menu Access).

**Comment by EkoJr** [comment]
SQL Request that is Producing error

```
SELECT wp_posts.* 
FROM   wp_posts 
        JOIN wp_icl_translations t 
        ON wp_posts.id = t.element_id 
            AND t.element_type = Concat('post_', wp_posts.post_type) 
WHERE  1 = 1 
        AND wp_posts.post_name = 'wpml-04' 
        AND wp_posts.post_type = 'apl_design' 
        AND ( ( wp_posts.post_status = 'publish' 
                OR wp_posts.post_status = 'future' 
                OR wp_posts.post_status = 'draft' 
                OR wp_posts.post_status = 'pending' 
                OR wp_posts.post_status = 'trash' 
                OR wp_posts.post_status = 'private'
			)
	    ) 
        AND ( ( t.language_code = 'en' 
                AND wp_posts.post_type IN ( 'post', 'page', 'attachment', 'apl_design' ) 
            ) 
            OR wp_posts.post_type NOT IN ( 'post', 'page', 'attachment', 'apl_design' )
        ) 
ORDER  BY wp_posts.post_date DESC 
```

**Comment by EkoJr** [comment]
With the APL_Design, majority of the issues were fixed using a `SitePress::set_element_language_details( $post_id, 'post_apl_design', null, ICL_LANGUAGE_CODE );`
